swagger: '2.0'
info:
  description: 综资接口能力开放需求资源接入能力查询
  version: '1.0'
  title: CSB迁_ZZ资源接入能力查询
  contact: {}
schemes: ['http']
host: '10.145.206.10:8999'
basePath: /openApi/csbq_zz/QueryResourceAccessAbility
tags:
  - name: QueryResourceAccessAbility-open-api-controller
    description: QueryResourceAccessAbility Open Api Controller
paths:
  /QueryResourceAccessAbility:
    post:
      tags:
        - QueryResourceAccessAbility-open-api-controller
      summary: 综资接口能力开放需求资源接入能力查询
      description: 综资接口能力开放需求资源接入能力查询
      operationId: createAttrSpecUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: req
          description: req
          required: true
          schema:
            $ref: '#/definitions/queryResourceAccessAbilityDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/queryResourceAccessAbilityResponseDTO'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false

definitions:
  queryResourceAccessAbilityDTO:
    type: object
    properties:
      requestXml:
        description: 请求业务报文(CDATA)
        $ref: '#/definitions/requestXmlDTO'
    title: queryResourceAccessAbilityDTO
  requestXmlDTO:
    type: object
    properties:
      requestdata:
        description: ''
        $ref: '#/definitions/requestdataDTO'
    title: requestXmlDTO
  requestdataDTO:
    type: object
    properties:
      address_full:
        type: string
        description: 地址全称
      address_road_name:
        type: string
        description: 路名
      address_lane:
        type: string
        description: 弄号
      address_sub_lane:
        type: string
        description: 支弄号
      address_house_no:
        type: string
        description: 门牌号
      address_building_no:
        type: string
        description: 幢栋
      address_floor:
        type: string
        description: 楼层
      address_room_no:
        type: string
        description: 室
    title: requestdataDTO

  queryResourceAccessAbilityResponseDTO:
    type: object
    properties:
      return:
        description: 返回业务报文(CDATA)
        $ref: '#/definitions/returnDTO'
    title: queryResourceAccessAbilityResponseDTO
  returnDTO:
    type: object
    properties:
      responsedata:
        description: ''
        $ref: '#/definitions/responsedataDTO'
    title: returnDTO
  responsedataDTO:
    type: object
    properties:
      errorCode:
        type: string
        description: 执行结果 0成功，非0失败
      errorMessage:
        type: string
        description: 失败原因
      resultSet:
        description: ''
        $ref: '#/definitions/resultSetDTO'
    title: responsedataDTO
  resultSetDTO:
    type: object
    properties:
      result:
        description: ''
        $ref: '#/definitions/resultDTO'
    title: resultSetDTO
  resultDTO:
    type: object
    properties:
      is_iptvability:
        type: string
        description: 是否具备IPTV能力
      is_optical:
        type: string
        description: 是否光网
      is_fttb_lan:
        type: string
        description: 是否FTTB+LAN
      is_maxspeed:
        type: string
        description: 最大可达速率
      is_fiber48:
        type: string
        description: 是否光网48小时
      is_ipv6:
        type: string
        description: 是否ipv6
      adsl_portcount:
        type: string
        description: ADSL空闲端口数
      fttb_lan_portcount:
        type: string
        description: FTTB+LAN（普通）空闲端口数
      fttb_lan_ponyy_portcount:
        type: string
        description: FTTB+LAN(pon)语音口空闲端口数
      fttb_lan_ponsj_portcount:
        type: string
        description: FTTB+LAN(pon)数据口空闲端口数
      gfftth_portcount:
        type: string
        description: 分光箱可用FTTH空闲端口数
    title: resultDTO
